# FROM tensorflow/tensorflow:latest-py3
FROM intelaipg/intel-optimized-tensorflow:latest-mkl-py3
RUN apt install -y rsync \
                   htop \
                   wget

RUN pip install pillow==5.4.1 \
                requests \
                tqdm \
                scipy

RUN pip install jupyter

RUN mkdir stylegan
WORKDIR /stylegan